name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: testechoscrets
      run: echo '${{ secrets.CODECOV_TOKEN }}'
    - run: echo ${{ secrets.CODECOV_TOKEN }}
    - name: Install pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.20.3

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Run test cases
      run: npm test

    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
